<h1 style="text-align:center";>Nuclei Technologies</h1>
<h2 style="text-align:right";>Done by B.Aakash<h2>

<h3>Problem Statement</h3>

<p>We want you to implement a face recognition system, don't worry we have a tutorial to guide you through it as well. Follow this video and try to implement a Face Recognition system using the pretrained model, you can use your own sample images from the internet to try it.</p>

<img src="http://www.camera-module.com/upfile/2019/06/20190616212440_891.png">


# Now for that we need to create a Dataset


In [2]:
import cv2
import numpy as np
import os



face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

name = input("Enter the Person's Name ....")

def face_extractor(img):
    # Function detects faces and returns the cropped face
    
    faces = face_classifier.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Cropping the images    
    for (x,y,w,h) in faces:
        x=x-10
        y=y-10
        cropped_face = img[y:y+h+50, x:x+w+50]

    return cropped_face


cap = cv2.VideoCapture(0)
count = 0 # for convenience for us to save the images so that it doesn't save the same file

while True:

    ret, frame = cap.read()
    if face_extractor(frame) is not None:
        count += 1
        face = cv2.resize(face_extractor(frame), (400, 400))

        # Save file in specified directory with unique name
        file_name_path = './Dataset/' + name +"-"+ str(count) + '.jpg'
        cv2.imwrite(file_name_path, face)

        # Put count on images and display live count
        cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        cv2.imshow('Face Cropper', face)
        
    else:
        #print("Face not found")
        pass

    if cv2.waitKey(1) == 13 or count == 100: #13 is the Enter Key
        break
        
cap.release()
cv2.destroyAllWindows()      
print("Collecting Samples Complete")

Enter the Person's Name ....Aakash_validation


# Face-Recognition

### Since I trained the model in kaggle for faster computation i have uploaded the dataset in kaggle and computed as shown below

In [30]:
# Kaggle link here



# Now lets us predict the model 

In [25]:
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model

def load_image(filename):
    img = load_img(filename, target_size=(224, 224))
    img = img_to_array(img)
    img = img.reshape(1, 224, 224, 3)
    img = img.astype('float32')
    return img

def run_example(path):
    img = load_image(path)
    # load model
    model = load_model('trained-model.h5')
    # predict the class
    result = model.predict(img)
    print(result[0])

[1. 0. 0.]


In [29]:
# entry point, run the example
run_example('Dataset/Aakash_validation-1.jpg')

[1. 0. 0.]


In [28]:
run_example("Dataset/Test/Raghava/Raghava_test-1.jpg")

[1.0000000e+00 4.5556967e-26 2.7625276e-33]
